version: '3.8'
services:
  app:
    container_name: django-app
    restart: always
    build: 
      context: .
    volumes:
      - .:/workspace:cached
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_PROD: False
      
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  volumes:
    postgres_data:
#    networks:
#      - db_network
#      - web_network
#  nginx:
#    container_name: nginx
#    restart: always
#    image: "nginx:latest"
#    ports:
#      - "5085:5085"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
#    networks:
#      - web_network
#    depends_on: 
#      - appseed-app
#networks:
#  db_network:
#    driver: bridge
#  web_network:
#    driver: bridge
 